# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)   

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)    


- task: PackerBuild@1
  displayName: 'Build immutable image'
  inputs:
    templateType: custom
    customTemplateLocation: '$(System.DefaultWorkingDirectory)/packer-template.json'
    customTemplateParameters: '{"subscription_id":"82c135d4-f813-4bec-a93e-60e4323918ee","client_id":"8a965742-d2ac-4123-8a02-780bd4fe49f6","client_secret":"1d77af71-0c0a-47dd-a311-f04b8606d72c","tenant_id":"72f988bf-86f1-41af-91ab-2d7cd011db47"}'
    ConnectedServiceName: 'DevOps Pipelines - ARM Horizontal Work(82c135d4-f813-4bec-a93e-60e4323918ee)'
    location: 'eastus2'
    storageAccountName: 'vmssstorage1234'
    azureResourceGroup: 'java-vmss'
    packagePath: '$(build.artifactstagingdirectory)'
    deployScriptPath: ''

- script: echo $(ManagedImageId)
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'

# - task: AzurePowerShell@5
#   inputs:
#     azureSubscription: 'DevOps Pipelines - ARM Horizontal Work(82c135d4-f813-4bec-a93e-60e4323918ee)'
#     ScriptType: 'InlineScript'
#     Inline: 'az vmss update --resource-group java-vmss --name java-four-scaleset --set virtualMachineProfile.storageProfile.imageReference.id=/subscriptions/82c135d4-f813-4bec-a93e-60e4323918ee/resourceGroups/java-vmss/providers/Microsoft.Compute/images/example-packer-img-1597261530'
#     azurePowerShellVersion: 'LatestVersion'

# - task: AzureVmssDeployment@0
#   inputs:
#     azureSubscription: 'DevOps Pipelines - ARM Horizontal Work(82c135d4-f813-4bec-a93e-60e4323918ee)'
#     action: 'Update image'
#     vmssName: 'java-four-scaleset'
#     vmssOsType: 'Linux'
#     imageUrl: '/subscriptions/82c135d4-f813-4bec-a93e-60e4323918ee/resourceGroups/java-vmss/providers/Microsoft.Compute/images/example-packer-img-1597261530'

# - task: PackerBuild@1
#   displayName: 'Build immutable image'
#   inputs:
#     templateType: 'builtin'
#     ConnectedServiceName: 'DevOps Pipelines - ARM Horizontal Work(82c135d4-f813-4bec-a93e-60e4323918ee)'
#     isManagedImage: true
#     managedImageName: 'vmss-packer-build'
#     location: 'eastus2'
#     storageAccountName: 'vmssstorage1234'
#     azureResourceGroup: 'java-vmss'
#     baseImageSource: 'default'
#     baseImage: 'Canonical:UbuntuServer:16.04-LTS:linux'
#     packagePath: '$(build.artifactstagingdirectory)'
#     deployScriptPath: 'install.sh'